version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_local
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  fastapi:
    build:
      context: ./fastapi_app  # path to FastAPI app directory with Dockerfile
    container_name: fastapi_app
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017  # Connection string to MongoDB in docker network
    depends_on:
      - mongo

  web:
    image: nginx:alpine
    container_name: simple_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - fastapi

volumes:
  mongo_data:
